Added profileController
anantgupta001/FoodApe pull request #49
Opened 2024-08-06 16:37 UTC by the-ayushgupta

Added profileController

2024-08-06 17:05 UTC, anantgupta001 requested changes
please go thorugh the required changes

2024-08-09 09:13 UTC, anantgupta001 requested changes
issues must be resolved before merging the PR

2024-08-09 09:13 UTC, anantgupta001 commented on Server/routes/profile.js
> +    '/perosnalInfo/deleteProfile',
set the correct route for this.

2024-08-09 09:13 UTC, anantgupta001 commented on Server/routes/profile.js
> +    '/perosnalInfo/likedFoods',
this too.

2024-08-09 09:13 UTC, anantgupta001 commented on Server/server.js
> +const editProfileRouter = require("./routes/profile.js");
name the variable correctly.

2024-08-09 09:13 UTC, anantgupta001 commented on Server/controllers/block.js
> +module.exports.show = (req, res) => {
name the function accordingly

2024-08-09 10:31 UTC, anantgupta001 requested changes
Issues must be resolved before merging this PR

2024-08-14 18:32 UTC, anantgupta001 approved these changes
LGTM

2024-08-14 19:49 UTC, ImmaNOOBie approved these changes

2024-08-14 20:06 UTC, merged